# Site settings
title : surf - Simulating Urban Flows
tagline: 'Understanding Urban Movements through Big Data and Social Simulation'
author :
  name : Nick Malleson
  github : nickmalleson
  twitter : nickmalleson
keywords: big data, agent-based modelling, simulation, urban flows


description: > # this means to ignore newlines until "baseurl:"
    This is the website for Nick Malleson’s surf research project, funded by ESRC Future Research Leaders scheme. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://surf.leeds.ac.uk" # the base hostname & protocol for your site
twitter_username: nickmalleson
github_username:  nickmalleson
email: n.s.malleson@leeds.ac.uk

# Build settings
markdown: kramdown
